### ISSUE TITLE
Segfault when scraping in OpenShift

### ISSUE THREAD

**Issue by zapodot** [marcinbudny/eventstore_exporter#15]
Hi! We have trouble running the exporter (v. 0.9.0) in OpenShift (Kubernetes) against single-node eventstore (docker tag: release-5.0.8) as it keeps segfaulting on scrape. 
Log:
`
time="2020-09-30T13:34:28Z" level=info msg="EventStore exporter configured" clusterMode=cluster enableParkedMessagesStats=true eventStoreURL="http://eventstore-server:2113 --cluster-mode=single" eventStoreUser=admin insecureSkipVerify=false port=9448 timeout=10s verbose=true
time="2020-09-30T13:34:36Z" level=info msg="Running scrape"
time="2020-09-30T13:34:36Z" level=debug msg="GET request to EventStore" url="http://eventstore-server:2113 --cluster-mode=single/subscriptions"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x72a037]

goroutine 28 [running]:
net/http.(*Request).SetBasicAuth(0x0, 0xc00002a0b0, 0x5, 0xc00002a074, 0x8)
	/usr/local/go/src/net/http/request.go:963 +0x37
main.get.func1(0xc000118280, 0x46, 0xc0002e6240, 0xc000118200)
	/go/src/github.com/marcinbudny/eventstore_exporter/eventstore_client.go:260 +0x645
created by main.get
	/go/src/github.com/marcinbudny/eventstore_exporter/eventstore_client.go:255 +0xcb
`
Is this a know issue?

**Comment by zapodot** [comment]
Found an issue in our helm template. Never mind!
